# The simplified syntax is 'fs_signature[:fs_driver]_key=value1,value2,...'
# where 'fs_signature' is the on-disk superblock identifier as exposed by blkid/udev
# and 'fs_driver' is (optionally) the filesystem type (a kernel driver) passed
# to the mount call. The 'key' is either "defaults", "allow" or "drivers".
#
# Refer to http://storaged.org/doc/udisks2-api/latest/mount_options.html
#

[defaults]
allow=exec,noexec,nodev,nosuid,atime,noatime,nodiratime,relatime,strictatime,lazytime,ro,rw,sync,dirsync,noload,acl,nosymfollow

vfat_defaults=shortname=mixed,utf8=1,showexec,flush
vfat_allow=uid,gid,flush,utf8,shortname,umask,dmask,fmask,codepage,iocharset,usefree,showexec

# common options for both the native kernel driver and exfat-fuse
exfat_defaults=iocharset=utf8,errors=remount-ro
exfat_allow=uid,gid,dmask,errors,fmask,iocharset,namecase,umask

# 'ntfs' signature, definitions for the legacy ntfs kernel driver and the ntfs-3g fuse driver
ntfs:ntfs_defaults=windows_names
ntfs:ntfs_allow=uid,gid,umask,dmask,fmask,locale,norecover,ignore_case,windows_names,compression,nocompression,big_writes

# 'ntfs' signature, the new 'ntfs3' kernel driver
ntfs:ntfs3_defaults=
ntfs:ntfs3_allow=uid,gid,umask,dmask,fmask,iocharset,discard,nodiscard,sparse,nosparse,hidden,nohidden,sys_immutable,nosys_immutable,showmeta,noshowmeta,prealloc,noprealloc,hide_dot_files,nohide_dot_files,windows_names,nocase,case
