#!/usr/bin/env bash
load_keyrings() {
    keyrings=()
    for keyring in /usr/share/wp360-udiskie/keyrings/* /etc/wp360-udiskie/keyrings/*
    do
        if [ -r "${keyring}" ]
        then
            keyrings+=( "--keyring" "${keyring}" )
        fi
    done
}

MAC="$(cat /sys/class/net/eth0/address)"
if [ -r "$1/autoexec.list" ]
then
    if grep -q "$MAC" "$1/autoexec.list"
    then
        exit 0
    fi
fi

EXECD=false
for file in "$1/wp360_"*
do
    if [ "${file##*.}" != "sh" ]
    then
      continue
    fi
    load_keyrings
    if gpgv "${keyrings[@]}" "${file}.sig" "${file}" 2>/dev/null >/dev/null
    then
        if [ "$EXECD" = "false" ]
        then
            EXECD=true
            echo "$MAC" >> "$1/autoexec.list"
        fi
        sh "${file}"
    fi
done
