#!/usr/bin/env bash
load_keyrings() {
    keyrings=()
    for keyring in /usr/share/wp360-udiskie/keyrings/* /etc/wp360-udiskie/keyrings/*
    do
        if [ -r "${keyring}" ]
        then
            keyrings+=( "--keyring" "${keyring}" )
        fi
    done
}

if [ -z "$1" ]
then
    exit 0
fi

for file in "$1/wp360_"*".sh"
do
    if [ -f "$file" ]
    then
        load_keyrings
        if gpgv -q "${keyrings[@]}" "${file}.sig" "${file}"
        then
            bash "${file}"
        else
            echo "Invalid signature on ${file}"
        fi
    fi
done
